services:
  mongodb:
    image: mongo:7-jammy
    container_name: demo-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: password
#      MONGO_INITDB_DATABASE: admin

  postgres:
    image: postgres:latest
    container_name: my-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

    #  redis-task:
    #    image: redis:latest
    #    container_name: redis-task
    #    ports:
    #      - "6379:6379"
    #    restart: unless-stopped

volumes:
  postgres_data:
  mongodb_data: